### ISSUE TITLE
Directory URL redirection

### ISSUE THREAD

**Issue by sjchmiela** [expo/fyi#1]
It would be great if the redirection logic could handle `http://expo.fyi/bundle-identifier/` the same as `http://expo.fyi/bundle-identifier`. I'm afraid developers copying/retyping the URL from the warning message may sometimes append the `/` suffix automatically.

At the moment, a request to `…/` URL times out instead of either redirecting to the appropriate article or showing a helpful error message.

**Comment by brentvatne** [comment]
fixed! https://github.com/expo/expo-fyi/commit/f0cc72ad23f8f4ef1884ccb110abe314f2af110b
