### ISSUE TITLE
Do i need a service account for each app?

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/fyi#101]
Do i need to create a service account for each app? or is the one just linked to my specific developer account?

**Comment by amandeepmittal** [comment]
It's dependent on how you manage those service account keys. In general, it is good idea to have one service account key per app. Take a look at Google's documentation on best practices on Service account keys management, especially, this section: https://cloud.google.com/iam/docs/best-practices-service-accounts#single-purpose.
