### ISSUE TITLE
https://expo.fyi/start from running expo start links to nothing

### ISSUE THREAD

**Issue by nathantew14** [expo/fyi#125]
After running `npx expo start`, one of the messages is this:

`› Scan the QR code above to open the project in a development build. Learn more`

Clicking the "learn more" link brings me to `https://expo.fyi/start` which gives me a 404.

Expo CLI version: 0.10.11

**Comment by amandeepmittal** [comment]
Hey @nathantew14, thanks for finding this bug and reporting it here. We'll fix it.

**Comment by nathantew14** [comment]
Hi @amandeepmittal, thanks for the response, it reassures me that the issues I raise are being looked at :)
