### ISSUE TITLE
Firebase warning

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/fyi#127]
I'm in the process of upgrading from Firebase 9 to Firebase 10 and have been using the following setup described in the [documentation](https://docs.expo.dev/guides/using-firebase/#using-firebase-js-sdk) without any hiccups, but when I upgraded to version 10.0.3 I'm seeing the following warning when running my application and when running my jest test suite.

Note: I have removed the persistence manager logic described [here](https://github.com/expo/fyi/blob/main/firebase-js-auth-setup.md#switching-to-the-react-native-persistence-manager) as it seems to no longer be necessary in version 10+, but the warning message below seems contradictory to what Firebase is specifying in their [latest release notes](https://firebase.google.com/support/release-notes/js#authentication).

For my project configuration I'm using the last version of expo (49.0.8). Perhaps this needs to go on the Firebase repo, but I figured other Expo users may encounter this and I haven't seen a solution yet on any of their threads. Do you have any recommendations @jacobhq @keith-kurak @amandeepmittal (adding you all since you all updated the document)?

![Screenshot 2023-08-23 at 8 27 36 AM](https://github.com/expo/fyi/assets/7604441/1574a9fc-ef7d-4a7a-b6b6-79b63e53fd09)

**Comment by amandeepmittal** [comment]
Thank you @hsubox76 for providing the info about the latest changes! Appreciate your effort and work with the Firebase JS SDK library.

Also, thank you @iM-GeeKy for bringing this to our attention. We'll update the FYI guide soon.
