### ISSUE TITLE
No matching version found for expo@~43.0.0.

### ISSUE THREAD

**Issue by Tadejo9** [expo/fyi#49]
From document:
> Do you want to integrate Expo modules in a React Native project without Unimodules? Add the "expo": "~43.0.0" dependency in package.json first.

I get the following error:
> No matching version found for expo@~43.0.0.

Is migration in bare project possible at this moment?

**Comment by matthops** [comment]
I'm also running into this issue.

**Comment by relez** [comment]
Hi there, in my case it failed cause of this:
```
Command `pod repo update` failed.
└─ Cause: Couldn't install: EXLocation » UMTaskManagerInterface. Ensure the CocoaPod "UMTaskManagerInterface" is installed in your project, then run `npx pod-install` to try again.
```
Any help?

**Comment by byCedric** [comment]
@Tadejo9 @matthops We are still in beta, [current latest (beta) version is `43.0.0-beta.4`](https://www.npmjs.com/package/expo/v/43.0.0-beta.4).

@relez did you try what it said? (`npx pod-install`) If that doesn't work, it's best to open a bug report in https://github.com/expo/expo. This repo is only for the FYI pages.

**Comment by relez** [comment]
> @Tadejo9 @matthops We are still in beta, [current latest (beta) version is `43.0.0-beta.4`](https://www.npmjs.com/package/expo/v/43.0.0-beta.4).
> 
> @relez did you try what it said? (`npx pod-install`) If that doesn't work, it's best to open a bug report in https://github.com/expo/expo. This repo is only for the FYI pages.

Yes, I did several times, but I was using beta.3 or beta.2! Anyways, I will wait until SDK 43 becomes stable.

Thanks!

**Comment by flexbox** [comment]
@Tadejo9 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
