### ISSUE TITLE
Facing errors in AppDelegate.h file -- Expo/Expo.h' file not found

### ISSUE THREAD

**Issue by Yandamuri** [expo/fyi#60]
I have followed all the migration steps as mentioned the docs. For Android it's working as expected. But I am getting mentioned error from `AppDelegate.h`.

<img width="751" alt="Screenshot 2022-01-06 at 12 34 05 PM" src="https://user-images.githubusercontent.com/31983789/148342622-82e6817c-cdcb-4c3a-87ad-65f211001505.png">

**Comment by jaquinocode** [comment]
I can't help, except to say that [this guide](https://dev.to/wbroek/migrate-from-react-native-unimodules-to-expo-modules-25c6) seems to be more helpful than expo's own guide.

**Comment by brentvatne** [comment]
hopefully that guide on dev.to was helpful!
