### ISSUE TITLE
Build error when running Android if BasePackageList.java is not deleted in Migrating to Expo modules

### ISSUE THREAD

**Issue by nakapon9517** [expo/fyi#65]
On migrating from expo-sdk42 to expo-sdk43 (react-native-unimodules->expo-modules)
https://github.com/expo/fyi/blob/main/expo-modules-migration.md

I didn't see this mentioned in the official instructions.
BasePackageList.java, which is originally referenced by MainApplication.java, must be deleted.
If you don't remove BasePackageList.java that is originally referenced in MainApplication.java, the react-native-unimodules related files used there will cause an error when building.

If this change is only local to me, please ignore it.
Thank you very much for your development.

**Comment by brentvatne** [comment]
hi there! sorry we missed this. i hope you were able to resolve the issue!
