### ISSUE TITLE
Update whats-in-the-sdk to mention EAS builds

### ISSUE THREAD

**Issue by maximveksler** [expo/fyi#75]
The page https://github.com/expo/fyi/blob/main/whats-in-the-sdk.md contains this text

> We can't include each and every native module out there because that would make for an extremely heavy toolbox (i.e. large [binary size](http://expo.fyi/managed-app-size) and maintenance cost). Instead, we only include native modules that we believe satisfy a wide range of needs for a large majority of developers. If you need a specific tool that isn't provided in the Expo toolbox, then you can always use the [bare workflow](https://docs.expo.dev/workflow/customizing/) and add any native module you'd like to your project, while still enjoying most of the benefits that Expo provides.

This text is a bit confusing, especially for people who are only starting with Expo since it recommended using bare for native code however this constraint was relaxed thanks to EAS build system and https://docs.expo.dev/development/introduction/

Does the copy in the fyi needs an update or is it correct?

**Comment by brentvatne** [comment]
thanks! this is indeed out of date. i've went ahead and updated this to point to https://docs.expo.dev/workflow/customizing/ :)

we're in the process of revamping most of our docs right now so you can expect this repo and our docs pages to improve continuously in coming months
