### ISSUE TITLE
EAS IOS build getting stuck

### ISSUE THREAD

**Issue by brunolcarlos** [expo/fyi#78]
All my IOS builds it's getting stuck and before to fisnish will stop with timeout

Waiting in queue
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■     | starting in about 130 minutes...

**Comment by brentvatne** [comment]
hi there! here's some information about build queues: https://expo.fyi/eas-build-queues

if this doesn't answer your question, i'd suggest going to https://chat.expo.dev/ and asking in the #build channel with more information
