### ISSUE TITLE
Expo build failure Plugin with id 'maven' not found

### ISSUE THREAD

**Issue by kcchan1680** [expo/fyi#80]
hi all
When I want to build my project to android but failure , first issue is stated Plugin with id 'maven' not found.
I checked from Internet and found some solutions, either one is stated to change maven-publish.
still failure but the log message still is same , Plugin with id 'maven' not found.

Can anyone help me how to solve it? please give me some advise, thanks

Here is the log message:
[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/@unimodules/core/android/build.gradle' line: 3
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':unimodules-core'.
[stderr] > Plugin with id 'maven' not found.
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] ==============================================================================

**Comment by brentvatne** [comment]
hi there! it's best to ask such questions on https://chat.expo.dev/ - this repository is meant for little fyi pages and not for support
