### ISSUE TITLE
fyi/firebase-migration-guide.md missing instructions

### ISSUE THREAD

**Issue by JamiiTelecom** [expo/fyi#94]
In the guide, please include a step to remove expo-firebase-core, failure to which IOS builds will keep failing

**Comment by amandeepmittal** [comment]
Hi @JamiiTelecom, we do not recommend installing `expo-firebase-core` library directly since it's used as peer dependency for other Expo Firebase packages. Hence, this is why it was not considered a part of the migration guide. However, we'll add a note to remove it.
