### ISSUE TITLE
Expo Go, ios simulator and @react-native-firebase/analytics conflict. Your JavaScript code tried to access a native module that doesn't exist.

### ISSUE THREAD

**Issue by liro** [expo/fyi#95]
Hello, I migrated from expo-firebase-analytics to @react-native-firebase/analytics. Now if I am running the ios simulator I catch an error:
```Invariant Violation: Your JavaScript code tried to access a native module that doesn't exist. 

If you're trying to use a module that is not supported in Expo Go, you need to create a development build of your app. See https://docs.expo.dev/development/introduction/ for more info.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:39 in handleError
at node_modules/expo/build/errors/ExpoErrorManager.js:25:19 in errorHandler
at node_modules/expo/build/errors/ExpoErrorManager.js:30:24 in <anonymous>
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:237:40 in guardedLoadModule
at http://192.168.0.42:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code
```
As far as i know @react-native-firebase/analytics does not support expo go. 
When I execute `expo start --ios` my app fails on import time at string: `import analytics from "@react-native-firebase/analytics";`.
App runs on simulator only if this string is commented.
The only option i see is to wrap import to a function like this:
`async function logEvent(){
  if(!Device.isDevice) return;
  import analytics from "@react-native-firebase/analytics";
  await analytics().logEvent('EVENT');
}`
But imports are allowed only on the top level.
So, how should I organise my codebase to use ios simuator and at the same time have @react-native-firebase/analytics for production?

**Comment by amandeepmittal** [comment]
Hi @liro, 

The `expo start --ios` command runs the project in Expo Go. The `@react-native-firebase/analytics` requires changes to native code for both platforms.

To resolve this, you'll have to create a development build to use React Native Firebase library. It is like creating a custom Expo Go version that includes or runs native libraries that you have included in your project. 

This is also a step mentioned in the [migration guide](https://github.com/expo/fyi/blob/main/firebase-migration-guide.md#create-a-development-build). Once you have installed the development build, you can use the command mentioned in [Test your changes](https://github.com/expo/fyi/blob/main/firebase-migration-guide.md#test-your-changes) section to trigger the development server once the development build is installed on the iOS simulator.
